server:
  port: 8081
spring:
  application:
    name: VehicleInsuranceSystem
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vehicle_insurance?serverTimezone=UTC
    username: root
    password: Password@12345
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
